if not exist "..\CODE\%1" mkdir "..\CODE\%1"
for %%f in (%1\*.*) do %TOOL%\IMAGE_MAGICK\convert -background white -alpha remove -alpha off -resize %2@ -interlace Plane -quality 70 -strip "%%f" "..\CODE\%1\%%~nf.jpg.3840.jpg"
for %%f in (%1\*.*) do %TOOL%\IMAGE_MAGICK\convert -background white -alpha remove -alpha off -resize %3@ -interlace Plane -quality 70 -strip "%%f" "..\CODE\%1\%%~nf.jpg.1920.jpg"
for %%f in (%1\*.*) do %TOOL%\IMAGE_MAGICK\convert -background white -alpha remove -alpha off -resize %4@ -interlace Plane -quality 70 -strip "%%f" "..\CODE\%1\%%~nf.jpg.1280.jpg"
for %%f in (%1\*.*) do %TOOL%\IMAGE_MAGICK\convert -background white -alpha remove -alpha off -resize %5@ -interlace Plane -quality 70 -strip "%%f" "..\CODE\%1\%%~nf.jpg.640.jpg"
for %%f in (%1\*.*) do %TOOL%\IMAGE_MAGICK\convert -background white -alpha remove -alpha off -resize %6@ -interlace Plane -quality 50 -strip "%%f" "..\CODE\%1\%%~nf.jpg.512.jpg"
