name: fluent_project
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  animations: ^2.0.7
  cached_network_image: ^3.2.3
  crypto: ^3.0.3
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  file_picker: ^5.3.3
  flutter_bloc: ^8.1.3
  go_router: ^10.1.0
  senselogic_gist: ^2.0.7
  shared_preferences: ^2.2.0
  supabase_flutter: ^1.10.13
  uuid: ^4.0.0
  sized_context: ^1.0.0+4
  universal_platform: ^1.0.0+1
  flutter_animate: ^4.2.0+1
  flextras: ^1.0.0
  extra_alignments: ^1.0.0+1
  bloc: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
