name: fluent_project
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  animations: ^2.0.8
  bloc: ^8.1.2
  cached_network_image: ^3.2.3
  crypto: ^3.0.3
  dio: ^5.3.2
  extra_alignments: ^1.0.0+1
  file_picker: ^6.1.1
  flextras: ^1.0.0
  flutter_animate: ^4.2.0+1
  flutter_bloc: ^8.1.3
  flutter_map: ^6.0.0
  flutter_phosphor_icons: ^0.0.1+6
  go_router: ^12.1.1
  intl: ^0.18.1
  senselogic_flow: ^0.0.1
  senselogic_gist: ^2.0.12
  shared_preferences: ^2.2.1
  sized_context: ^1.0.0+4
  styled_widget: ^0.4.1
  supabase_flutter: ^1.10.18
  textstyle_extensions: ^2.0.0-nullsafety
  universal_platform: ^1.0.0+1
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
